version: "3.9"

services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/vol/web
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - ALLOWED_HOSTS=${DJANGO_ALLOWED_HOSTS}
      - EMAIL_USE_TLS=${APP_EMAIL_USE_TLS}
      - EMAIL_HOST=${APP_EMAIL_HOST}
      - EMAIL_PORT=${APP_EMAIL_PORT}
      - EMAIL_HOST_USER=${APP_EMAIL_HOST_USER}
      - EMAIL_HOST_PASSWORD=${APP_EMAIL_HOST_PASSWORD}
      - DEFAULT_FROM_EMAIL=${APP_DEFAULT_FROM_EMAIL}
      - DEFAULT_TO_EMAIL=${APP_DEFAULT_TO_EMAIL}
      - EMAIL_DEFAULT=${APP_EMAIL_DEFAULT}
      - AWS_ACCESS_KEY_ID=${APP_AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${APP_AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${APP_AWS_STORAGE_BUCKET_NAME}
      - AWS_S3_REGION_NAME=${APP_AWS_S3_REGION_NAME}
      - AWS_CLOUDFRONT_CUSTOM_DOMAIN=${APP_AWS_CLOUDFRONT_CUSTOM_DOMAIN}

  proxy:
    build:
      context: ./proxy
    restart: always
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - static-data:/vol/static
      - letsencrypt:/etc/letsencrypt
      - certbot:/var/www/html
      

volumes:
  static-data:
  letsencrypt:
  certbot: