# Generated by Django 4.0.10 on 2023-12-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20231206_0305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='file',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_photo',
            field=models.FileField(null=True, upload_to='uploads/profile_photos/'),
        ),
    ]
