# Generated by Django 4.0.10 on 2024-09-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_user_file_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rules',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SELLER', 'Seller')], default='SELLER', max_length=20),
        ),
    ]
