# Generated by Django 4.0.10 on 2024-09-21 04:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_rules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('SELLER', 'Seller')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='rules',
        ),
        migrations.AddField(
            model_name='user',
            name='rules',
            field=models.ManyToManyField(to='user.role'),
        ),
    ]
