# Generated by Django 4.0.10 on 2024-09-21 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_role_remove_user_rules_user_rules'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='role',
            table='user_roles',
        ),
    ]
