# Generated by Django 4.0.10 on 2024-09-21 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_role_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rules',
            new_name='roles',
        ),
    ]
