# Generated by Django 4.0.10 on 2024-09-27 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_rules_user_roles'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_staff',
            new_name='is_deleted',
        ),
    ]
