# Generated by Django 4.0.10 on 2024-10-08 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_is_staff_user_is_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='user',
            name='state',
        ),
        migrations.RemoveField(
            model_name='user',
            name='street',
        ),
    ]
