---
name: Checks

on: [push]

jobs: 
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    env:
      DB_HOST: db
      DB_NAME: dev_db
      DB_USER: devuser
      DB_PASS: id2j98dj123djw9d82
      DJANGO_SECRET_KEY: django_secret_key
      DJANGO_ALLOWED_HOSTS: 127.0.0.1
      APP_EMAIL: contato@email.com.br
      APP_DOMAIN: dominio.com.br
      APP_EMAIL_USE_TLS: 1
      APP_EMAIL_HOST: smtp.googlemail.com
      APP_EMAIL_PORT: 587
      APP_EMAIL_HOST_USER: contato@email.com.br
      APP_EMAIL_HOST_PASSWORD: abc123
      APP_DEFAULT_FROM_EMAIL: contato@email.com.br
      APP_DEFAULT_TO_EMAIL: DjangoAPI
      APP_EMAIL_DEFAULT: contato@email.com.br
      APP_AWS_ACCESS_KEY_ID: AWS_ACCESS_KEY_ID
      APP_AWS_SECRET_ACCESS_KEY: AWS_SECRET_ACCESS_KEY
      APP_AWS_STORAGE_BUCKET_NAME: django-static
      APP_AWS_S3_REGION_NAME: us-east-1
      APP_AWS_CLOUDFRONT_CUSTOM_DOMAIN: cloudfront.net
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: make test
      - name: Lint
        run: make style